### ISSUE TITLE
Scenario with empty step fails with NoSuchElementException

### ISSUE THREAD

**Issue by dromosys** [grasshopper7/cucumber-pdf-plugin#11]
[INFO] STARTED CUCUMBER PDF REPORT GENERATION PLUGIN
java.util.NoSuchElementException
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:970)
        at java.base/java.util.Collections.max(Collections.java:674)
        at tech.grasshopper.data.PDFCucumberReportDataGenerator.createScenario(PDFCucumberReportDataGenerator.java:94)
        at tech.grasshopper.data.PDFCucumberReportDataGenerator.generateReportData(PDFCucumberReportDataGenerator.java:69)
        at tech.grasshopper.CucumberPDFReportPlugin.execute(CucumberPDFReportPlugin.java:108)

**Comment by grasshopper7** [comment]
This could be error checked to throw an exception to stop the report generation. Will have a look. But this is kind of pointless to have a scenario without steps or features without scenarios etc etc, just because gherkin allows it.

**Comment by dromosys** [comment]
The report generation stops at this point, I'm suggesting to handle this, write out a warning to the logs and continue report generation

**Comment by grasshopper7** [comment]
I can write out the message in the console. But report still will not be generated in such a case as there are more checks in place in the code which actually generates the pdf report. To accommodate this I will need to change a lot of code. 
Currently I will not be willing to take this up.

**Comment by dromosys** [comment]
Fair enough

**Comment by grasshopper7** [comment]
You can try placing checks in this repository - https://github.com/grasshopper7/cucumber-json-report-data-generator. Have a look at PDFCucumberReportDataGenerator.java as a starting point.
